# Uncomment the next line to define a global platform for your project
  platform :ios, '13.0'

target 'ITEA_12' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ITEA_12
  pod 'FirebaseUI/Auth'
  pod 'Alamofire'

end
