# Uncomment the next line to define a global platform for your project
  platform :ios, '13.0'

target 'ITEA_13' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ITEA_13
  pod 'Firebase/Auth'
  pod 'Firebase/Analytics'
  pod 'Firebase/Crashlytics'
  pod 'SwiftyJSON', '~> 4.0'

end
