# Uncomment the next line to define a global platform for your project
  platform :ios, '13.0'

target 'ITEA_14' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ITEA_14
  pod 'FirebaseUI/Auth'
  pod 'Firebase/Firestore'
  pod 'Alamofire', '~> 5.2'
  pod 'SwiftyJSON', '~> 4.0'
  
end
